export const FETCH_ALL_ITINERARY_ITEMS = 'FETCH_ALL_ITINERARY_ITEMS';
export const CREATE_ITINERARY_ITEM = 'CREATE_ITINERARY_ITEM';
export const UPDATE_ITINERARY_ITEM = 'UPDATE_ITINERARY_ITEM';
export const DELETE_ITINERARY_ITEM = 'DELETE_ITINERARY_ITEM';
