export const CREATE_TRIP = 'CREATE_TRIP';
export const UPDATE_TRIP = 'UPDATE_TRIP';
export const DELETE_TRIP = 'DELETE_TRIP';
export const FETCH_ALL_TRIPS = 'FETCH_ALL_TRIPS';
export const SET_CURRENT_TRIP = 'SET_CURRENT_TRIP';